version: '3.8'

services:
  # Servicio para PRODUCCIÓN
  eureka-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-angular-app
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - microservices-network

  # Servicio para DESARROLLO con hot-reload
  eureka-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: eureka-angular-dev
    ports:
      - "4200:4200"
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./angular.json:/app/angular.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./tsconfig.app.json:/app/tsconfig.app.json:ro
      - ./tailwind.config.ts:/app/tailwind.config.ts:ro
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - NG_CLI_ANALYTICS=false
    restart: unless-stopped
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
    name: udemy-apirest-micro_microservices-network